"""'创建数据表'

Revision ID: 1d6d3457b2a8
Revises: 
Create Date: 2018-05-27 22:44:57.802758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d6d3457b2a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('signature', sa.String(length=200), nullable=True),
    sa.Column('nick_name', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(length=50), nullable=True),
    sa.Column('publish_news_count', sa.Integer(), nullable=True),
    sa.Column('fans_count', sa.Integer(), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('news_classes', sa.Integer(), nullable=True),
    sa.Column('abstract', sa.String(length=50), nullable=True),
    sa.Column('news_pic', sa.String(length=50), nullable=True),
    sa.Column('msg', sa.Text(), nullable=True),
    sa.Column('check_statu', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['check_statu'], ['check_news.id'], ),
    sa.ForeignKeyConstraint(['news_classes'], ['news_classes.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('to_user_user',
    sa.Column('origin_user_id', sa.Integer(), nullable=False),
    sa.Column('follow_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follow_user_id'], ['user_info.id'], ),
    sa.ForeignKeyConstraint(['origin_user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('origin_user_id', 'follow_user_id')
    )
    op.create_table('news_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('about', sa.Integer(), nullable=True),
    sa.Column('msg', sa.Text(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['about'], ['news.id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['news_comment.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('to_news_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'news_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('to_news_user')
    op.drop_table('news_comment')
    op.drop_table('to_user_user')
    op.drop_table('news')
    op.drop_table('user_info')
    op.drop_table('news_classes')
    op.drop_table('check_news')
    # ### end Alembic commands ###
