"""'修改新闻审核表结构'

Revision ID: d2127741bc0e
Revises: 1d6d3457b2a8
Create Date: 2018-05-27 23:04:42.744533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2127741bc0e'
down_revision = '1d6d3457b2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check_news', 'create_time')
    op.drop_column('check_news', 'isdelete')
    op.drop_column('check_news', 'publish_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_news', sa.Column('publish_time', mysql.DATETIME(), nullable=True))
    op.add_column('check_news', sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('check_news', sa.Column('create_time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
